# This file is designed for deployment on Coolify.
# It sets up the Gemini CLI OpenAI service and a Redis cache.

services:
  gemini-cli-openai:
    image: drnit29/gemini-cli-openai:latest
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      # Dashboard authentication credentials (required for dashboard access)
      - DASHBOARD_USERNAME=${DASHBOARD_USERNAME}
      - DASHBOARD_PASSWORD=${DASHBOARD_PASSWORD}
      # NOTE: Other environment variables (GCP_SERVICE_ACCOUNT, OPENAI_API_KEY, thinking features)
      # should be configured through the dashboard interface at /dashboard
      # to ensure proper override and persistence in the data/.env file
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      start_period: 40s
      retries: 3

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 15s
      timeout: 5s
      start_period: 20s
      retries: 3